import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import BackgroundImage from '/public/bg-grid.png';
import Hero from "@/components/hero";

const lexendSans = Lexend({
  variable: "--font-lexend-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jon Rey Galera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendSans.variable} antialiased`}
      >
        <Header/>
        <Hero src={BackgroundImage} alt="Jon Rey Galera"/>
        <div className="pt-16">
          {children}
        </div>
      </body>
    </html>
  );
}
